In [1]:
pip install tensorflow


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import tensorflow as tf

# Paso 1: Definir las dimensiones
filas = int(input("Cantidad de filas: "))
columnas = int(input("Cantidad de columnas: "))

# Paso 2: Crear 2 matrices aleatorias del 1 al 20
matriz1 = tf.random.uniform([filas, columnas], minval=1, maxval=21, dtype=tf.int32)
matriz2 = tf.random.uniform([filas, columnas], minval=1, maxval=21, dtype=tf.int32)

# Paso 3: Sumar matrices (misma forma)
suma = matriz1 + matriz2

# Paso 4: Multiplicar matrices (forma compatible)
# OJO: Para que funcione la multiplicación de matrices, usamos matriz2 transpuesta
multiplicacion = tf.matmul(matriz1, tf.transpose(matriz2))

# Paso 5: Mostrar todo
print("\nMatriz 1:\n", matriz1.numpy())
print("\nMatriz 2:\n", matriz2.numpy())
print("\nSuma:\n", suma.numpy())
print("\nMultiplicación:\n", multiplicacion.numpy())


Matriz 1:
 [[11  1]
 [12 12]
 [19 20]]

Matriz 2:
 [[ 4  8]
 [ 1 20]
 [ 9  5]]

Suma:
 [[15  9]
 [13 32]
 [28 25]]

Multiplicación:
 [[ 52  31 104]
 [144 252 168]
 [236 419 271]]
